# -*- coding: utf-8 -*-
"""Edge-map generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L2Lkusq_JgjyYtzvBKqzwWGm5-Jz9lZd
"""

import os, cv2

def make_edges(inp_folder, out_folder, size=512):
    os.makedirs(out_folder, exist_ok=True)
    for fname in os.listdir(inp_folder):
        if not fname.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.tif', '.tiff')):
            continue
        path = os.path.join(inp_folder, fname)
        img = cv2.imread(path, cv2.IMREAD_COLOR)
        if img is None:
            continue
        img = cv2.resize(img, (size, size), interpolation=cv2.INTER_AREA)
        edges = cv2.Canny(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY), 100, 200)
        out_path = os.path.join(out_folder, f"{os.path.splitext(fname)[0]}_edges.png")
        cv2.imwrite(out_path, edges)
        print("Created:", out_path)

make_edges("data/photos/raw", "data/photos/edges")
make_edges("data/buildings/raw", "data/buildings/edges")
make_edges("data/manuscripts/images", "data/manuscripts/edges")

from IPython.display import Image as JImage, display
import random, glob

samples = random.sample(glob.glob("data/photos/edges/*.png"), 3)
for s in samples:
    display(JImage(filename=s))

